<select id="langue-nom" name="langueNom" required>
    <option value="3N">🇬🇧 Anglais SG</option>
    <option value="A7">🇦🇺 Australien</option>
    <option value="AF">🇿🇦 Afrikaans</option>
    <option value="AR">🇸🇦 Arabe</option>
    <option value="BG">🇧🇬 Bulgare</option>
    <option value="CA">🇪🇸 Catalan</option>
    <option value="CS">🇨🇿 Tchéque</option>
    <option value="DA">🇩🇰 Danois</option>
    <option value="DE">🇩🇪 Allemand</option>
    <option value="EL">🇬🇷 Grec</option>
    <option value="EN">🇬🇧 Anglais</option>
    <option value="ES">🇪🇸 Espagnol</option>
    <option value="ET">🇪🇪 Estonien</option>
    <option value="FI">🇫🇮 Finnois</option>
    <option value="FR">🇫🇷 Francais</option>
    <option value="HE">🇮🇱 Hébreu</option>
    <option value="HI">🇮🇳 Hindi</option>
    <option value="HR">🇭🇷 Croate</option>
    <option value="HU">🇭🇺 Hongrois</option>
    <option value="ID">🇮🇩 Indonésien</option>
    <option value="IS">🇮🇸 Islandais</option>
    <option value="IT">🇮🇹 Italien</option>
    <option value="JA">🇯🇵 Japonais</option>
    <option value="KK">🇰🇿 Kazakh</option>
    <option value="KO">🇰🇷 Coréen</option>
    <option value="LT">🇱🇹 Lituanien</option>
    <option value="LV">🇱🇻 Letton</option>
    <option value="MS">🇲🇾 Malais</option>
    <option value="NL">🇳🇱 Néerlandais</option>
    <option value="NO">🇳🇴 Norvégien</option>
    <option value="PL">🇵🇱 Polonais</option>
    <option value="RO">🇷🇴 Roumain</option>
    <option value="RU">🇷🇺 Russe</option>
    <option value="SH">🇷🇸 Serbe (latin)</option>
    <option value="SK">🇸🇰 Slovaque</option>
    <option value="SL">🇸🇮 Slovène</option>
    <option value="SR">🇷🇸 Serbe</option>
    <option value="SV">🇸🇪 Suédois</option>
    <option value="TH">🇹🇭 Thai</option>
    <option value="TR">🇹🇷 Turc</option>
    <option value="UK">🇺🇦 Ukrainien</option>
    <option value="VI">🇻🇳 Vietnamien</option>
    <option value="Z1">Z1 Réserve client</option>
    <option value="ZF">🇹🇼 Chinois trad.</option>
    <option value="ZH">🇨🇳 Chinois</option>
</select>